### ISSUE TITLE
MetaZ doesn't work with iOS 10.13

### ISSUE THREAD

**Issue by SjeikRob** [griff/metaz#169]
MetaZ (Version 1.0a15 (13.11.27.14.8abfa83)) doesn't work with the new operating system (10.13). Is there an update coming? Thanx

**Comment by griff** [comment]
There is already an update [1.0 Beta 34](https://github.com/griff/metaz/releases/download/v1.0.beta-34/MetaZ-1.0.beta-34.zip). I have not put it in the official release channel because I need to reimplement TheTVDB plugin since it is going break in a few days and want to have that done before releasing version 1.0.

**Comment by SjeikRob** [comment]
Thank you for your quick response! Now it works again.... 👍🏻😎
