### ISSUE TITLE
Access Existing Tags in saveChanges:delegate:queue:

### ISSUE THREAD

**Issue by jmcintyre** [griff/metaz#17]
I'm adding some enhancements to TV Show tagging into APDataProvider (mostly to automate disc, album, and album artist to follow iTunes patterns automatically), but it appears that in the method saveChanges:delegate:queue: I only have access to changed tags. Do you have any recommendations on how to get access to the other tags that were already set, or optimally a list of the tags changed and unchanged tags merged together?

**Comment by griff** [comment]
The easiest right now is just to change the saveChanges:delegate:queue: method to take the full meta data object as argument instead of just the changes so you have access to what you need.

In the long term I have been thinking about changing the object that stores the meta data so that it is possible to get access to the individual layers (right now you only get a stacked view) and so that I can support new layers. The new layers I want to support are one for data extracted from the filename and one for having values bound together like for a TV Show the Artist tag automatically gets the value of the show name .

**Comment by griff** [comment]
Actually after looking at the code I found that saveChanges:delegate:queue: already gets all meta data like you want. The MetaEdits class contains changes but it also provides a reference to the loaded data via the provider property (not the best of names)

**Comment by griff** [comment]
Meta data is stored and managed internally using 2 classes that both implement the MetaData protocol.

First is the MetaLoaded class which contains tags loaded from the file and give access to those tags both directly and using Key-Value Coding. So both `[data title]` and `[data valueForKey:@"title"]` return the same value. MetaLoaded objects also provides a reference to the data provider that created that object via the owner property. And it has a shortcut for getting all tags supported by that provider (which it currently claims is all known tags).

The second class is MetaEdits which layers on top of a MetaLoaded object (the provider property) and intercepts changes. I say intercept because when a tag has not been changed MetaEdits calls through to the MetaLoaded object. So if the title tag hasn't been changed `[edits title]` returns the loaded title value and if it has been changed the new value. On MetaEdits objects there are also setters for all tags which follow the normal Obj-C naming convention; eg. `[edits setTitle:newTitle]`, and a way to query if a tag has been changed that returns a BOOL; eg. `[edits titleChanged]`

One important thing to note is that this access to tags that MetaLoaded and MetaEdits provides is entirely dynamic. Nowhere is the title method directly implemented. Instead when created MetaLoaded and MetaEdits objects get told what tags to support and intercept calls to access those tags.

**Comment by jmcintyre** [comment]
That should work out better than what I was doing before. I'm putting together additional features similar to how the track is automatically set to be the same as the episode number for tv shows. In this case, if show and season data are available, it automatically sets Artist, Album, Album Artist, and Disc appropriately to match iTunes style. Let me know if you have any interest in this and I can put together a pull request. I have found it to speed thing up significantly (especially with Album Artist which is set to Show, Season #).
