### ISSUE TITLE
Cannot open .mp4 files after updating from Mac OS 12.6.x to Mac OS 10.13.4.  I'm really going to miss using this app.

### ISSUE THREAD

**Issue by SkyEmperor** [griff/metaz#188]

**Comment by LDMartin1959** [comment]
I hadn't made that connection, but I too can not get anything to load. I get the app's loading "throbber" but it never goes anywhere. The app isn't locking up, it just won't load anything. I thought I'd screwed up something. Nice to know it isn't that and just me. Hopefully we get a resolution soon because MetaZ is an essential application.

**Comment by griff** [comment]
It is already solved but because I am working on getting the update framework setup again you need to manually download the fixed version for now. See #174 for more details.

**Comment by LDMartin1959** [comment]
Excellent. As I say, MetaZ is an essential app and I know everyone appreciates your dedication to keep it updated.

**Comment by griff** [comment]
I am closing this issue as resolved
