### ISSUE TITLE
Compile Delay

### ISSUE THREAD

**Issue by jmcintyre** [griff/metaz#235]
The new Sparkle process adds a significant delay to each build, even if Sparkle doesn't need to be updated.

**Comment by griff** [comment]
Do we even need the `carthage update` in the Xcode build?

The travis build already starts with a `carthage bootstrap` which should download and build the frameworks specified in `Cartfile` and `Cartfile.resolved` so as long as those are up to date and in sync the travis build should not need the additional `carthage update` in the Xcode build process.

For developers (i need to write an updated build instruction) requiring calling `carthage update` manually as part of the build instructions before you build with Xcode seems ok.

We could also change the `carthage update` to `carthage build --cache-build` since that will download and rebuild only the changed or new frameworks in `Cartfile` and `Cartfile.resolved`. I just tested and that is exactly how that command works.

**Comment by jmcintyre** [comment]
I want to try some things to see if I can make the automation work, but if not, we can probably remove it.

**Comment by jmcintyre** [comment]
I was able to revert back, so this can be closed.
