### ISSUE TITLE
Movies being tagged in iTunes as "Home Videos"

### ISSUE THREAD

**Issue by tstall2** [griff/metaz#34]
Since iTunes was updated to iTunes 11, any new additions into iTunes get tagged as "Home Videos" by meta Z even when I have it set to "Movies" in the video/video Type attribute.

**Comment by griff** [comment]
Well i seems that the video types have changed names so that Movies becomes Home Movies and Short Film becomes Movies.

So a short term workaround is to set the video type in MetaZ to Short Film.

But this has its own problems since the search uses the video type to find out if it should search for a tv show or a movie and Short Film is counted as none of those. So I would recommend that you set the video type to Movies while using search and editing data and then just before you add the file to the queue you change the video type to Short Film.

I will work on a more permanent fix for this issue.

**Comment by tstall2** [comment]
Short Film worked like a champ.

**Comment by griff** [comment]
I am closing this since alpha 13 just released renames "Movie" to "Home Movie" and "Short Film" to "Movie" like it is in iTunes 11.
