### ISSUE TITLE
Unable to Search

### ISSUE THREAD

**Issue by awuestenfeld** [griff/metaz#50]
I am unable to search after uploading my list of movies/TV Shows.  I've unchecked TagChimp since I understand the site isn't working, but I am still getting zero results.

Thanks for the help!

**Comment by griff** [comment]
Can you make sure that the video type is either Movie or TV Show? Because if it is anything else you won't get any search results.

Recently I renamed the Movie video type to Home Movie because that is how that type is interpreted by iTunes 11. You might be effected by this change since I forgot to change the search plugins to also search when the video type is Home Movie.

**Comment by awuestenfeld** [comment]
When I import them to MetaZ I am selecting "TV Show"... is that what you're asking?

**Comment by dino73** [comment]
Just to add in, I'm getting exactly the same thing when I'm searching for TV shows. When I do searches for Movies it works absolutely great, but I'm getting nothing for even the most popular TV shows.

**Comment by griff** [comment]
@awuestenfeld yes that was what I was asking.

To both of you: Are the TV show, season number and optionally the episode number fields filled out? The plugin that searches for TV shows on TheTVDB will only search when at least the TV Show and Season fields are filled out.

If those fields are filled out could you either send me, at brian@maven-group.org, the log that you can open from the menu Help -> View Log or look in it yourself and see if it reports any errors.

**Comment by dino73** [comment]
All good, its working. Thank you.

**Comment by awuestenfeld** [comment]
I just emailed you the log as well as the window showing the search results

**Comment by dino73** [comment]
Brian,

Thanks for that, it sorted it.
