### ISSUE TITLE
FSPathCopyObjectAsync callbacks with ARC

### ISSUE THREAD

**Issue by epologee** [griff/metaz#6]
Hi, I can't think of another way to send you a message, so please forgive me for using the issue board although this is **not an issue of MetaZ**.

I'm looking for example implementations of FSPathCopyObjectAsync and your project is the only clear one on github. I'm talking about the [`NSFileManager+MZAsync`](https://github.com/griff/metaz/blob/develop/Framework/src/NSFileManager%2BMZAsync.m) category. I have been trying to port the category and the depending objects to ARC and although the actual copying works, the callback method `MZCopyFSPathFileOperationStatusProc` is never called. I'm assuming this is because some object is incorrectly released by ARC, but there could be something else going on. I am holding on the return object of the `copyItemAsyncAtPath:toPath:destName:options:statusChangeInterval:error:` method, so that's not it.

Would you know how to get this to work under a project with ARC enabled? You can see my attempt at https://gist.github.com/9421769313130bf060a9.
Sorry to bother you with this, but I'd be very grateful if you could help.
Cheers,
EP.

**Comment by griff** [comment]
I don't know much about ARC. Haven't used it but have read about it. I can though find at least one problem in your gist:

```
clientContext.retain = CFRetain;
clientContext.release = CFRelease;
clientContext.copyDescription = CFCopyDescription;
```

As far as I know you can only use CFRetain and CFRelease with Objective-C objects that have toll-free-bridges to CoreFoundation objects. And since the original MZRetain and MZRelease contain calls to release and retain which isn't allowed under ARC you have a problem.

One way around this problem is to wrap the MZAsyncOperation in an object that does support toll-free-bridging like NSArray.

```
MZAsyncOperation* ret = [[MZAsyncOperation alloc] initWithManager:self];
CFArrayRef wrap = (__bridge_retained CFArrayRef)[NSArray arrayWithObject:ret];

FSFileOperationClientContext clientContext;
clientContext.version = 0;
clientContext.info = wrap;
clientContext.retain = CFRetain;
clientContext.release = CFRelease;
clientContext.copyDescription = CFCopyDescription;

[ret schedule];
OSStatus status = FSPathCopyObjectAsync(
    ret.operation,
    src,
    dst,
    (__bridge CFStringRef)destName,
    flags,
    MZCopyFSPathFileOperationStatusProc,
    statusChangeInterval,
    &clientContext
);
CFRelease(wrap);
```

You then also need to replace the line `MZAsyncOperation* op = (__bridge MZAsyncOperation*)info;` with:

```
NSArray* wrap = (__bridge NSArray*)info;
MZAsyncOperation* op = [wrap objectAtIndex:0];
```

I hope this helps you but please bear in mind I haven't tested any of this code.

**Comment by griff** [comment]
Strike what I said above. After reading up on it I found out you can apparently use CFRetain and CFRelease on any object.

I'll try and look into this in more detail later today.

**Comment by griff** [comment]
I made a simple test program earlier today because the whole async file copy category haven't really been used in MetaZ so I had no idea if it actually worked just as it was without any ARC related changes.

Luckily it worked as expected on my Snow Leopard machine so I wanted to then try and get it to work on my Lion machine with ARC (which required me to first update Xcode to 4.2). And when I did the exact changes you had done in your gist it worked just like it had without ARC.

So my conclusion is that you must be using the category wrong in some way maybe giving it incorrect arguments.
My complete test code and project is here: https://gist.github.com/1687827
It is setup to get a callback every second and outputs progress data with each callback using NSLog

**Comment by epologee** [comment]
This is awesome, thanks for taking this much time to look into it. Your code works fine on my machine too, so I must've done something else wrong. I'm going to take my time to check for the differences, but this solves it for sure! Thanks a lot man!
