### ISSUE TITLE
UK Date Formats

### ISSUE THREAD

**Issue by posaune** [griff/metaz#60]
Hi - I'm finding MetaZ really useful, but have encountered one problem.

Having processed a TV programme with a broadcast date of, say, 23 May 1964 and added it to iTunes, it correctly shows as Sat 23 May 1964.

However, accessing the same programme from an Apple TV via Home Sharing, the date is shown as 5/23/1964 instead of 23/5/1964.

TV programmes bought through iTunes show up correctly in UK date format; just those processed through MetaZ show the correct date, but in US format.

For reference, here's the version info:
MetaZ Version 1.0a13 (12.12.04.06.20c53b9)
Mac Mini, 10.8.3, Region: UK
iTunes, 11.0.2
Apple TV3, 5.2.1, Lang: British English, TZ: London

Thanks!

**Comment by TomStenson** [comment]
As far as I can tell, this is an Apple problem. I have the same: UK date in iTunes, but displayed as US dates in AppleTV - and it doesn't matter if the film is bought via iTunes or added by myself. I've even tried switching my AppleTV to another language, such a German, French or Swedish, but it will still display US dates. This has been the case since Apple TV generation 1. Sloppy programming by Apple, I would say.

**Comment by posaune** [comment]
Thanks for that info - I've done some digging and we seem to be stuck with US dates when using Home Sharing. Bought programmes show up fine through TV Programmes, but not via Home Sharing. I have an Apple support ticket open for his and have added (anonymously) your feedback to it.
