### ISSUE TITLE
Can't open m4v files on 10.5 PPC

### ISSUE THREAD

**Issue by nabeards** [griff/metaz#65]
Opening any m4v file fails on a PPC Mac mini running 10.5.8 and 1.0a13 of MetaZ. Seems like the call to AtomicParsley is assuming Intel, and I can find no documentation that the app should be Intel only.

Received the error window that the File is In An Unsupported Format.

The Console error is basically:
MetaZ[370] [lvl=1] -[MZTaskOperation standardErrorGotData:] AtomicParsley stderr 
**\* NSTask: Task create for path 'MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider/Contents/Resources/AtomicParsley' failed: 86, "Bad CPU type in executable".  Terminating temporary process.

Please let me know if there is additional info I can provide!

Thanks,
Neil

**Comment by nabeards** [comment]
I did try drag-and-drop to the Dock icon and the files list as well as using the '+' button.

**Comment by nabeards** [comment]
I've done some additional testing and it looks like the AtomicParsley included in the app build doesn't support PPC (I tried executing it directly and received the same error). Do you have the source for your version of AtomicParsley available to update? I'd like to help if possible.

**Comment by nabeards** [comment]
OK, I've got a Mac setup to build AtomicParsley. However, when I build the latest branch, it seems to not know about the --long-description switch you send it. Do you know what version and/or branch you are expecting to have in the build?

**Comment by griff** [comment]
Sadly no I don't know how the AtomicParsley binary was built since I have only ever had it in binary form. Taken from MetaX when I first started this project.

I have long wanted to replace AtomicParsley with [MP4v2](https://code.google.com/p/mp4v2/) since that would enable faster writes and a codebase I would be able to debug and fix bugs in when encountering weird files. Right now because I use a binary that is kind of a black box my options are really limited when it comes to problems with that which is frustrating. But I have been really caught up with work for some time and so MetaZ has suffered a bit.

**Comment by nabeards** [comment]
No problem Brian, thanks for the info! I was able to finally build AtomicParsley for the G4 with some minor changes to work with MetaZ. It looks like MP4v2 would be awesome to include. I'd like to get a script put together to auto-rip my DVDs and auto-tag them with MetaZ. I'll let you know how it turns out. (-:

Let me know if you'd like the AtomicParsley I built that works on PPC.
