### ISSUE TITLE
Plug-Ins

### ISSUE THREAD

**Issue by Treverr** [griff/metaz#81]
I've looked and found the plug ins on the site, but I don't really understand how to download / install them or how it all works with metaz, anyone have an idea? Since TheMovieDB isn't working I was going to reply on IMDB plug in but I need it installed to use it and I'm not sure how to go about that.

**Comment by griff** [comment]
Unless there is some other plugin for MetaZ that I am unaware of no IMDB plugin has ever been completed. There is some code in the repository that was the beginning of an IMDB plugin but since such a plugin would have to break the terms and services of IMDB to work and TheMovieDB data was good enough it was never completed.

On a side note I have just fixed ThMovieDB plugin and will be doing a release within a day or two.
