### ISSUE TITLE
Search for "les miserables" does not return any matches

### ISSUE THREAD

**Issue by garglebutt** [griff/metaz#82]
Per title where the second e has an acute accent in the official title.

I suggest there is an opportunity to improve metaz with some fuzzy matching using unicode de-normalisation. A search for "Les misÃ©rables" returns results but is rather difficult to type on a keyboard. :)

**Comment by griff** [comment]
Since I don't do the actual matching this would be tricky to do. What I actually do is just send the search data to some external services, [TheTVDB](http://thetvdb.com), [TheMovieDB](http://themoviedb.com) and [tagChimp](http://tagchimp.com), and just show the results that they return. Going from "Les Misérables" to "les miserables" is easy but going the other way requires that I do one search call for each possible combination of accented characters in "les miserables".

I also believe that TheMovieDB and TheTVDB already does fuzzy matching like this and I have forwarded your sugestion to the guy running the tagChimp service.

Please note TheMovieDB search is broken in the currently released version of MetaZ (see #74) and I will be making a new release that fixes this within a day or two.
